### ISSUE TITLE
old race bug?

### ISSUE THREAD

**Issue by drnickw** [rogernclarke/Rankings#41] opened 2018-10-21 16:18 UTC
See Nat youth champs 2017 9.9.17 - positions start at 61??
Lots of old races seem to have no results and several have dodgy positions??
Data looks OK from my end I think

**Comment by drnickw** [comment] 2018-10-21 19:03
Sorry = realise now you were working on the DB, I`m sure all is fine.

**Comment by rogernclarke** [comment] 2018-10-21 19:06
Nat Youth champs looks fine, but you are right about rides not showing for older events. Just trying to work out why!

**Comment by rogernclarke** [comment] 2018-10-22 16:15
I've worked out what the problem is, thankfully, as I was getting worried about this one!

When you page through a list it sets the offset for the next query - so if you are displaying 20 items in a list the offset for page 2 is 20, page 3 is 40 etc. When you displayed the Youth Champs for 2017 I would take a bet that you clicked through from page 3 of a list of events. It didn't reset the offset when going to get the riders so only retrieved riders from 61 onwards.

I'll have to work out how to reset the offset correctly, but for now if you navigate to an event with a more specific search then I think it would bring back the riders correctly.

Well spotted!

**Comment by rogernclarke** [comment] 2018-10-22 16:43
I think this is fixed now - reopen it if you find it isn't.

**Closed by rogernclarke** 2018-10-22 16:43 UTC
Labels: bug
